services:
  employee-service-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-service-web
    ports:
      - "5174:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
